In [1]:
import torch
from egg.core import Interaction
import os
from glob import glob

In [12]:
root_dir = '/home/dominik/Nextcloud/020_Masterstudium/Language Technology/LT2402_Master Thesis/experiments/runs/language-games/'
model_dir = os.path.join(root_dir, 'discriminator/')
dataset_dir = os.path.join(model_dir, 'dale-2/')
run_dir = os.path.join(dataset_dir, '2023-08-10_09-34-38_discriminator/')
train_interaction_path = glob(os.path.join(run_dir, "interactions/", "train/", "epoch*/", "interaction*"))[0]
test_interaction_path = glob(os.path.join(run_dir, 'interactions/', 'validation/', 'epoch*/', 'interaction*'))[0]

In [13]:
train_interaction: Interaction = torch.load(train_interaction_path)
test_interaction: Interaction = torch.load(test_interaction_path)

# for image_id, message in zip(test_interaction.aux_input['image_id'],
#                                      test_interaction.message):
#     print(message.max(dim=1).indices)

print(set([tuple(message.max(dim=1).indices.tolist()) for message in test_interaction.message]))
for message in test_interaction.message:
    print(message.max(dim=1).indices)

{(9, 0), (4, 0), (2, 0), (8, 0), (6, 0), (1, 0)}
tensor([4, 0])
tensor([2, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([2, 0])
tensor([2, 0])
tensor([2, 0])
tensor([4, 0])
tensor([2, 0])
tensor([2, 0])
tensor([2, 0])
tensor([4, 0])
tensor([4, 0])
tensor([2, 0])
tensor([4, 0])
tensor([2, 0])
tensor([4, 0])
tensor([2, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([2, 0])
tensor([4, 0])
tensor([2, 0])
tensor([2, 0])
tensor([4, 0])
tensor([2, 0])
tensor([2, 0])
tensor([2, 0])
tensor([2, 0])
tensor([4, 0])
tensor([6, 0])
tensor([2, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([2, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([2, 0])
tensor([4, 0])
tensor([4, 0])
tensor([2, 0])
tensor([2, 0])
tensor([4, 0])
tensor([4, 0])
tensor([2, 0])
tensor([2, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([4, 0])
tensor([2, 0])
tensor([4, 0])
tensor([2, 0])
tensor